// AUTO-GENERATED by scripts/build-changelog.mjs — DO NOT EDIT BY HAND.
// Regenerate via `npm run changelog:build` (also runs as prebuild/predev).

import type { ChangelogEntry } from './changelog-types'

export const generatedChangelog: ChangelogEntry[] = [
  {
    "version": "unreleased",
    "date": "2026-05-02",
    "tag": null,
    "commits": [
      {
        "hash": "c533179",
        "date": "2026-05-02",
        "subject": "feat(admin): test plan accionable + persistente en modal de release notes"
      },
      {
        "hash": "069978b",
        "date": "2026-05-02",
        "subject": "feat(admin): badge \"Abandonada\" + indicador de intentos en lista de PCs"
      },
      {
        "hash": "6be381f",
        "date": "2026-05-02",
        "subject": "feat(admin/metrics): show Unity builds + alert system, default 7d"
      },
      {
        "hash": "3b64b0c",
        "date": "2026-05-02",
        "subject": "fix(admin): renderizar release notes con typography + remark-gfm"
      },
      {
        "hash": "05390e2",
        "date": "2026-05-02",
        "subject": "feat(admin): mostrar release notes en builds list y PC detail"
      },
      {
        "hash": "67509b9",
        "date": "2026-05-01",
        "subject": "feat(admin): tabla de faults + passive collision en scoring config (#17)"
      },
      {
        "hash": "5946199",
        "date": "2026-05-01",
        "subject": "feat(kiosk): kioskId estable + autocuración + UX clara en verificación"
      },
      {
        "hash": "e848c2e",
        "date": "2026-05-01",
        "subject": "fix(kiosk): regenerar QR en sesión muerta + wake en visibilitychange"
      },
      {
        "hash": "472adb9",
        "date": "2026-05-01",
        "subject": "feat(admin/simuladores): agregar categoría \"Vehículo de Emergencia\" (#13)"
      },
      {
        "hash": "f76c6d7",
        "date": "2026-05-01",
        "subject": "feat(admin): agrega input gearChangeWithoutClutch al panel /admin/scoring"
      },
      {
        "hash": "8b431c0",
        "date": "2026-05-01",
        "subject": "feat(admin/simuladores): agregar categoría \"Vehículo de Emergencia\""
      },
      {
        "hash": "233238a",
        "date": "2026-04-30",
        "subject": "feat(admin/versiones): modal \"Ver detalles\" con release notes en markdown"
      },
      {
        "hash": "f812f23",
        "date": "2026-04-30",
        "subject": "feat(admin/sidebar): ocultar Controladores y Firmware del menú"
      },
      {
        "hash": "d9ebf00",
        "date": "2026-04-29",
        "subject": "feat(citas): pasar licenseType, cancelación, UI configuración del calendario (#11)"
      },
      {
        "hash": "ffab8e5",
        "date": "2026-04-29",
        "subject": "feat(admin/pcs): instalar build desde la página de PCs (per-PC + bulk) (#10)"
      },
      {
        "hash": "f4c279d",
        "date": "2026-04-29",
        "subject": "feat(admin/pcs): UI de rename remoto + refactor a updatePC unificado (#9)"
      },
      {
        "hash": "207b5e1",
        "date": "2026-04-29",
        "subject": "feat(admin/pcs): habilitar sort en UID/Actualización/Ambiente y subir contraste"
      },
      {
        "hash": "fb975eb",
        "date": "2026-04-29",
        "subject": "feat(admin/pcs): add column sorting to PCs table"
      },
      {
        "hash": "712a988",
        "date": "2026-04-29",
        "subject": "feat(admin/simuladores): mostrar versión de Unity de la PC en cada card"
      },
      {
        "hash": "9c67019",
        "date": "2026-04-24",
        "subject": "feat(admin/pcs): tabs Resumen / Versiones / Calibración + Logs"
      },
      {
        "hash": "962c474",
        "date": "2026-04-24",
        "subject": "feat(admin/pcs): página de logs Unity por PC"
      },
      {
        "hash": "3d2aac1",
        "date": "2026-04-24",
        "subject": "fix(portal): aclarar 'Examen teórico' en labels de estado del trámite"
      },
      {
        "hash": "17b042c",
        "date": "2026-04-23",
        "subject": "fix(portal/examen): reflejar estado real del trámite en /examen/[id]"
      },
      {
        "hash": "dd597f1",
        "date": "2026-04-23",
        "subject": "fix(portal): dashboard lista todos los trámites activos + alinea stepper"
      },
      {
        "hash": "005a620",
        "date": "2026-04-23",
        "subject": "fix(portal): overflow horizontal en móvil del flujo ciudadano"
      },
      {
        "hash": "f1e3dcd",
        "date": "2026-04-23",
        "subject": "ci: promover main a stage automáticamente"
      },
      {
        "hash": "adc472b",
        "date": "2026-04-23",
        "subject": "feat(admin/operaciones): módulo de monitoreo en vivo enfocado en PCs"
      },
      {
        "hash": "9d2796a",
        "date": "2026-04-22",
        "subject": "fix(portal): bugs de flujo ciudadano reportados"
      },
      {
        "hash": "eb4b846",
        "date": "2026-04-22",
        "subject": "feat(portal): perfil obligatorio + costos dinámicos de licencia"
      },
      {
        "hash": "a74a19c",
        "date": "2026-04-21",
        "subject": "feat(admin/integraciones): healthcheck en lista + probador de token en detalle"
      },
      {
        "hash": "9235d05",
        "date": "2026-04-21",
        "subject": "refactor(admin): migrar páginas /admin/* a TanStack Query"
      },
      {
        "hash": "d425c26",
        "date": "2026-04-21",
        "subject": "docs(portal): documentar estrategia SSR y actualizar TODO/almacenamiento"
      },
      {
        "hash": "df6ad02",
        "date": "2026-04-21",
        "subject": "fix(admin-api): alinear tipo de listarTramites con backend paginado"
      },
      {
        "hash": "b828e7c",
        "date": "2026-04-21",
        "subject": "chore(portal): instalar @tanstack/react-query + devtools"
      },
      {
        "hash": "43fb1be",
        "date": "2026-04-21",
        "subject": "feat(admin/integraciones): grid de cards + página de detalle"
      },
      {
        "hash": "5a05bb7",
        "date": "2026-04-21",
        "subject": "fix(portal): eliminar redirects de next.config.js que chocan con middleware"
      },
      {
        "hash": "085b2c4",
        "date": "2026-04-21",
        "subject": "feat(portal): middleware rewrite para limpiar URL /portal/* del ciudadano"
      },
      {
        "hash": "20956be",
        "date": "2026-04-21",
        "subject": "refactor(portal): SSR en landing, tipo-licencia y solicitud"
      },
      {
        "hash": "76bc97c",
        "date": "2026-04-21",
        "subject": "feat(admin): rotar tokens + historial de llamadas en /admin/integraciones"
      },
      {
        "hash": "43c767a",
        "date": "2026-04-21",
        "subject": "feat: capturar datos oficiales en solicitud + admin de tokens de integración"
      },
      {
        "hash": "1d42d87",
        "date": "2026-03-25",
        "subject": "fix: audit — 2GB file size limit + abort controller on polling"
      },
      {
        "hash": "6b6e50d",
        "date": "2026-03-25",
        "subject": "feat: show interrupted exam status in admin — yellow badge + info note"
      },
      {
        "hash": "f125fef",
        "date": "2026-03-25",
        "subject": "feat: Unity builds management — upload, deploy to PCs, status tracking"
      },
      {
        "hash": "71bd35c",
        "date": "2026-03-24",
        "subject": "feat: tabla de infracciones para ciudadanos + sesiones en admin"
      },
      {
        "hash": "5a0928d",
        "date": "2026-03-24",
        "subject": "fix: sidebar highlights only the most specific matching route"
      },
      {
        "hash": "90bf3e5",
        "date": "2026-03-24",
        "subject": "feat: environment dropdown in PCs list — promote PCs between dev/stage/prod"
      },
      {
        "hash": "2e7f368",
        "date": "2026-03-24",
        "subject": "fix: use USER_PASSWORD_AUTH instead of SRP for admin login"
      },
      {
        "hash": "fb09730",
        "date": "2026-03-23",
        "subject": "chore: include pending local changes — scoring page, admin-api, SimulatorCard updates"
      },
      {
        "hash": "daa6737",
        "date": "2026-03-23",
        "subject": "feat: add simulator management pages — simulators list, detail, PCs"
      },
      {
        "hash": "4fbbf3c",
        "date": "2026-02-26",
        "subject": "fix: pasar rango de mes actual a GET /admin/citas para evitar 400"
      },
      {
        "hash": "1a3d375",
        "date": "2026-02-24",
        "subject": "feat: move face verification to protected route with Identity Pool"
      },
      {
        "hash": "c8b156a",
        "date": "2026-02-24",
        "subject": "simplify: /verificar abre Face Liveness directo sin código de cita"
      },
      {
        "hash": "0095914",
        "date": "2026-02-23",
        "subject": "feat: add kiosk check-in flow with face verification"
      },
      {
        "hash": "7985141",
        "date": "2026-02-23",
        "subject": "feat: mejorar vista firmware — agrupación por ambiente, íconos por dispositivo, UX de deploy"
      },
      {
        "hash": "e8154cc",
        "date": "2026-02-22",
        "subject": "fix: corregir animaciones de scroll en landing page"
      },
      {
        "hash": "26cd087",
        "date": "2026-02-19",
        "subject": "feat: rediseño página detalle dispositivo IoT — tabs Estado/Pruebas/Calendario"
      },
      {
        "hash": "14126e9",
        "date": "2026-02-19",
        "subject": "feat: rediseño visual dashboard IoT — contraste online/offline, filtros, barra compacta"
      },
      {
        "hash": "154abd9",
        "date": "2026-02-19",
        "subject": "feat: gráficas de performance API en dashboard de métricas"
      },
      {
        "hash": "99ef7bb",
        "date": "2026-02-19",
        "subject": "feat: dashboard de métricas con recharts en /admin/metrics"
      },
      {
        "hash": "77a7cec",
        "date": "2026-02-19",
        "subject": "feat: rediseño dashboard IoT con tarjetas de simuladores"
      },
      {
        "hash": "a3a2eba",
        "date": "2026-02-19",
        "subject": "fix: alinear interfaces frontend con respuesta real de API IoT"
      },
      {
        "hash": "6bd8771",
        "date": "2026-02-19",
        "subject": "feat: dashboard IoT para gestión de dispositivos y OTA"
      },
      {
        "hash": "fb33b1f",
        "date": "2026-02-19",
        "subject": "feat: admin user management UI + JSON resilience fix"
      },
      {
        "hash": "667be8a",
        "date": "2026-02-19",
        "subject": "feat: integrate real AWS backend (Cognito auth, API endpoints, adapters)"
      },
      {
        "hash": "e09c31e",
        "date": "2026-02-19",
        "subject": "feat: redirect authenticated citizens from / to /portal"
      },
      {
        "hash": "1272b87",
        "date": "2026-02-18",
        "subject": "feat: reestructurar jerarquía del dashboard ciudadano"
      },
      {
        "hash": "c61f433",
        "date": "2026-02-18",
        "subject": "feat: move remaining citizen pages under /portal/ for shared layout"
      },
      {
        "hash": "a9f222c",
        "date": "2026-02-18",
        "subject": "feat: reorder tramite steps — license type selection before personal data"
      },
      {
        "hash": "26a0bf3",
        "date": "2026-02-16",
        "subject": "refactor: simplify header to single CTA button"
      },
      {
        "hash": "f463d5d",
        "date": "2026-02-16",
        "subject": "feat: add citizen portal, tramite flow, brochure, and admin modules"
      },
      {
        "hash": "888d130",
        "date": "2026-02-16",
        "subject": "fix(portal): improve signup visibility on citizen auth page"
      },
      {
        "hash": "a477c1f",
        "date": "2026-02-16",
        "subject": "feat: replace admin PIN login with username/password split-screen auth"
      },
      {
        "hash": "ee44a94",
        "date": "2026-02-16",
        "subject": "refactor: replace emoji icons with Lucide components in admin licencias"
      },
      {
        "hash": "118f6f1",
        "date": "2026-02-16",
        "subject": "feat: update homepage steps, reorder sections, and add subtle scroll animations"
      },
      {
        "hash": "9803644",
        "date": "2026-02-16",
        "subject": "style: restyle admin portal to match apostille-admin design system"
      },
      {
        "hash": "5acc67b",
        "date": "2026-02-04",
        "subject": "feat: Add theoretical exam system for driver's license"
      },
      {
        "hash": "e8bb4c7",
        "date": "2026-02-04",
        "subject": "Initial commit: Portal Simulador de Licencias de Conducir"
      }
    ]
  }
]
